### ISSUE TITLE
Peer-to peer code review

### ISSUE THREAD

**Issue by ritikarawat220** [AbdusSattar-70/To-Do-List#10]
### Hy ✋🏻 
**You have done great job on this project .. everything works perfectly fine 💯** 

Just one suggestion .. try to implement the ENTER button when user type the todo list.. it would be better for the user 
Other than that its perfect 👍🏻

cheers, happy coding 😄

**Comment by AbdusSattar-70** [comment]
Hello, @ritikarawat220 and all team members, 
Thanks for giving me the best suggestion. I have done this job #14
