### ISSUE TITLE
Readme file Missing some headings or need some changes 

### ISSUE THREAD

**Issue by codeWithHyder** [AbdusSattar-70/To-Do-List#2]
- Great work so far
- As we went through it ,Readme file missing some headings or need slight changes . at Project Title , and Author name .

**Comment by AbdusSattar-70** [comment]
Hello, My morning session team members @codeWithHyder @sumon766 and @eyoab01 - Thanks for investing time to review my project and giving me proper suggestions. I have solved issue #2
