### ISSUE TITLE
Good work so far

### ISSUE THREAD

**Issue by codeWithHyder** [AbdusSattar-70/To-Do-List#7]
Documentation required , as it describes the parts of codebase clearly

**Comment by AbdusSattar-70** [comment]
Thanks @codeWithHyder, Please would you like to say more details?

**Comment by codeWithHyder** [comment]
your work is very great 🥇 
MY SUGGESTIONS , each part should have given documentation  eg;  addtask,deletion part, clearAll .. , so that if any new trainee wants to go through your code may not feel hectic to understand your codebase

**Comment by AbdusSattar-70** [comment]
Hello @codeWithHyder, I will implement your suggestions on my project.
### Thanks for giving me such a best advice.
